FROM iofog/proxy:latest

LABEL org.opencontainers.image.description Proxy
LABEL org.opencontainers.image.source=https://github.com/datasance/skupper-proxy
LABEL org.opencontainers.image.licenses=Apache-2.0
CMD ["node", "/opt/app-root/bin/iofog.js"]