parameters:
  - name: 'arch'
    type: string
    default: X86
  - name: 'repository'
    type: string
  - name: 'imageTag'
    type: string

steps:
  - script: |
      echo "${{ parameters.repository }}:${{ parameters.imageTag }}" > ${{ parameters.arch }}_DOCKER_IMAGE
      echo "${{ parameters.repository }}:${{ parameters.imageTag }}"
    displayName: 'Save Docker image name and tag to ${{ parameters.arch }}_DOCKER_IMAGE into artifacts'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      TargetFolder: $(Build.ArtifactStagingDirectory)
      Contents: |
        ${{ parameters.arch }}_DOCKER_IMAGE
      OverWrite: true
    displayName: 'artefacts to publish'

  - task: Docker@2
    displayName: 'build and push docker image'
    inputs:
      containerRegistry: 'Edgeworx DockerHub'
      repository: ${{ parameters.repository }}
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile.iofog'
      tags: |
        $(Build.SourceBranchName)
        ${{ parameters.imageTag }}
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: ${{ parameters.arch }}
    displayName: 'publish artifacts'
